blank_issues_enabled: false
contact_links:
  - name: General Discussion
    url: https://github.com/polymath-ventures/applejokebugs/discussions
    about: For general discussion about Apple bugs or the site
